baseurl             = "https://nathanschucher.com/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Nathan Schucher"
title               = "Nathan Schucher"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-90175355-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "Nathan Schucher"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "I make things with code some of the time"
email        = ""
faviconfile  = "img/leaf.ico"
github       = "//github.com/nschuc"
highlightjs  = true
lang         = "en"
linkedin     = "//www.linkedin.com/in/nathan-schucher-89905460"
twitter      = "//twitter.com/nschucher"
selfIntro    = "look at this guy, drinking his coffee, don't you want to hire him?"

# gravatar             = ""                # do not use in the same time as avatar
avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"]            # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
